### ISSUE TITLE
Bookmarks no longer colour correctly

### ISSUE THREAD

**Issue by K-Meech** [mobie/platybrowser-datasets#68]
Bookmarks e.g. https://github.com/mobie/platybrowser-datasets/blob/master/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L553 no longer colour correctly. They still add extra tables / recognise the column, but don't apply the selected lut.

@constantinpape - could you possibly try changing 'glasbey' to 'Glasbey' in the bookmark? (I can't edit files on the arendt share so it's a bit hard for me to check)

**Comment by constantinpape** [comment]
That would be incosistent though, we use lower case for all the colors.
Anyway, I gave you permissions for `/g/arendt/EM_6dpf_segmentation/platy-browser-data/data/1.0.1/misc` so you should be able to change it locally to test now.

**Comment by K-Meech** [comment]
I just tested this quickly on the arendt share, and changing it to upper case fixes the issue for me. Upper case is also how the luts are stated here: https://github.com/tischi/imagej-utils/blob/master/src/main/java/de/embl/cba/tables/color/ColoringLuts.java I imagine this means a number of bookmarks are affected this way...

**Comment by constantinpape** [comment]
Thanks for checking!

> https://github.com/tischi/imagej-utils/blob/master/src/main/java/de/embl/cba/tables/color/ColoringLuts.java I imagine this means a number of bookmarks are affected this way...

Hmm, this means that the definition of colors in java and in the jsons got out of sync at some point. I don't really know why, because we agreed to have all the colors in the jsons lower capital at some point, e.g. `glasbey` or `randomFromGlasbey`.

Also, the colors in the `images.json` are specified this way, so I am a bit confused why this is inconsistent with the bookmarks.

Anyway, I can change this but we should make sure beforehand that everything is consistent.

**Comment by tischi** [comment]
I think we said lower case for the Bookmarks indeed.
Let me check why that could have changed...

**Comment by tischi** [comment]
@K-Meech 
I guess this is only for the fancy olors, like Glasbey and not for simple colours like white and magenta, right?

**Comment by tischi** [comment]
Can you guys provide me with an example Bookmark in the platybrowser that I can use for testing.
I have to do something else now but will fix it after lunch.

**Comment by constantinpape** [comment]
You just need a bookmark with glasbey in "color by column", right?
Then take "Figure 5C: Gene clustering full body".

**Comment by constantinpape** [comment]
Just to add to the incosistencies with colormaps: The `randomFromGlasbey` we use for prospr doesn't work anymore, see #69.

(Smaller case `glasbey` in images.json still works though: the colormap for the cell segmentation is correctly displayed https://github.com/mobie/platybrowser-datasets/blob/master/data/1.0.1/images/images.json#L2608)

**Comment by tischi** [comment]
> "Figure 5C: Gene clustering full body"

This works again with this change: 
```
		if ( metadata.color != null )
		{
			// within MoBIE the convention is Captial first letter:
			// see class ColoringLuts
			metadata.color = WordUtils.capitalize( metadata.color );
		}
```
