### ISSUE TITLE
Prospr coloring doesn't work as expected

### ISSUE THREAD

**Issue by constantinpape** [mobie/platybrowser-datasets#69]
All prospr volumes are currently added with a white color map, see 

![prospr-colors](https://user-images.githubusercontent.com/4263537/93571604-fb9bf700-f994-11ea-8235-b928c5a6f556.png)

Instead, they should be added with a random color map drawn from glasbey.
This is specified by the color name `randomFromGlasbey`, see
https://github.com/mobie/platybrowser-datasets/blob/master/data/1.0.1/images/images.json#L15

This used to work. Is this maybe related to #68?

**Comment by tischi** [comment]
This should have stopped working a long time ago, when we introduced the new Bookmark parsing.
I added new code to fix it:
```
        ARGBType argbType;
        if ( metadata.color.equals("RandomFromGlasbey") )
        {
            final GlasbeyARGBLut glasbeyARGBLut = new GlasbeyARGBLut();
            final int argb = glasbeyARGBLut.getARGB( createRandom( metadata.imageId ) );
            argbType = new ARGBType( argb );
        }
        else
        {
            argbType = ColorUtils.getARGBType( metadata.color );
        }

        if ( argbType != null ) bdvStackSource.setColor( argbType );
```

**Comment by constantinpape** [comment]
> This should have stopped working a long time ago, when we introduced the new Bookmark parsing.

Yes, quite possible that we overlooked this for some time.

**Comment by K-Meech** [comment]
Yes - I haven't checked the bookmarks in a long time either - so could easily have changed a while ago.

**Comment by constantinpape** [comment]
This is working now.
