### ISSUE TITLE
Id remapping in bookmarks 

### ISSUE THREAD

**Issue by vzinche** [mobie/platybrowser-datasets#70]
selectedLabelIds remapping in bookmarks doesn't work properly.
Examples: [Figure 2C](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L134), [Figure 6A and 6C](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L717), [Figure 6B and 6D](https://github.com/mobie/platybrowser-datasets/blob/4ad227b475fc90e9aedde1cdde76c1686dc97959/data/1.0.1/misc/bookmarks/manuscript_bookmarks.json#L759).

For the last two the correct ids would be:
* Figure 6A and 6C: 32130 and 31989
* Figure 6B and 6D: 6757 and 6905

**Comment by tischi** [comment]
@constantinpape 
Is that if the version of the segmentation changes?
How do we handle this?

**Comment by constantinpape** [comment]
> Is that if the version of the segmentation changes?

Yes.

> How do we handle this?

I have a script that does this, but it seems like it didn't work properly for all bookmarks.
I will check what's going wrong.

**Comment by constantinpape** [comment]
Ok, I might have found the issue:
We have changed the bookmark layout a while ago and I haven't adapted the scripts that migrates the bookmarks for it yet.

I will check later if that actually fixes it.

**Comment by constantinpape** [comment]
Yes, that was the issues. Ids in the bookmarks should all be fixed now.
