### ISSUE TITLE
bookmarks not showing up

### ISSUE THREAD

**Issue by HernandoMV** [mobie/platybrowser-datasets#81]
Version 1.0.1
When trying to display the bookmarks, I can only see default
![image](https://user-images.githubusercontent.com/6049065/113107873-517f1080-91fc-11eb-95c4-ebb1debba640.png)

**Comment by tischi** [comment]
> Yes, the additional bookmarks need to be loaded via the context menu:
"Right click"->"Load additional bookmarks"->"Load from project"->"manuscript_bookmarks.json"

Which is in fact not so cool for the publication!
@K-Meech could we make it such that they are part of the default bookmarks?

**Comment by K-Meech** [comment]
@constantinpape is already on this! I think this is done now

**Comment by constantinpape** [comment]
Yes, the bookmarks are back in the defaults.
